version: "3.7"

services:
  solr:
    image: docker.io/library/solr:9
    restart: always
    environment:
      SOLR_HEAP: 1G
    volumes:
      - "./collection:/webarchive"
      - "./solr/solr_home/:/var/solr/data"
    expose:
      - 8983
    ports:
      - 8983:8983
    userns_mode: keep-id:uid=8983,gid=8983
    command:
      - "-c"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/"]

  solrwayback:
    image: ghcr.io/deutsche-nationalbibliothek/solrwayback-compose:solrwayback-main
    restart: always
    volumes:
      - "./collection:/webarchive"
      - "./solrwayback/properties/solrwaybackweb.properties:/root/solrwaybackweb.properties"
      - "./solrwayback/properties/solrwayback.properties:/root/solrwayback.properties"
    expose:
      - 8080
    ports:
      - 8080:8080

  indexer:
    image: ghcr.io/deutsche-nationalbibliothek/solrwayback-compose:warc-indexer-main
    environment:
      SOLR_URL: http://solr:8983/solr/netarchivebuilder
      STATUS_ROOT: /status
    volumes:
      - "./collection:/webarchive"
      - "./warc-indexer-status:/status"

# This is a custom option for podman to tell that it doesn't start the compose in a pod, since userns_mode is not allowed in pods.
x-podman:
  in_pod: false
