version: '3'

env:
  IMAGEBUILD_CMD: podman
  COMPOSE_CMD: podman-compose
  SOLRWAYBACK_RELEASE: 5.1.0

tasks:
  default:
    desc: Lists all available tasks
    cmds:
      - task -a

  run:
    desc: Execute the compose environment
    cmds:
      - "{{.COMPOSE_CMD}} up"

  build:
    desc: Build all images
    cmds:
      - task: build:solrwayback
      - task: build:warc-indexer

  prepare:
    desc: Prepare the directories with the required artifacts
    cmds:
      - task: prepare:solr
      - task: prepare:solrwayback
      - task: prepare:warc-indexer

  download:
    desc: Download and extract the solrwayback package
    cmds:
      - curl -L -o solrwayback_package_{{.SOLRWAYBACK_RELEASE}}.zip https://github.com/netarchivesuite/solrwayback/releases/download/{{.SOLRWAYBACK_RELEASE}}/solrwayback_package_{{.SOLRWAYBACK_RELEASE}}.zip
      - unzip solrwayback_package_{{.SOLRWAYBACK_RELEASE}}.zip
      - mv $( zipinfo -1 solrwayback_package_{{.SOLRWAYBACK_RELEASE}}.zip | head -1 ) solrwayback_package

  prepare:warc-indexer:
    desc: Move files from the solrwayback package to the warc-indexer folder
    dir: warc-indexer
    cmds:
      - cp ../solrwayback_package/indexing/warc-indexer.sh .
      - cp ../solrwayback_package/indexing/warc-indexer-3.3.1-jar-with-dependencies.jar .
      - cp ../solrwayback_package/indexing/config3.conf .

  build:warc-indexer:
    desc: Build the warc-indexer image
    dir: warc-indexer
    cmds:
      - "{{.IMAGEBUILD_CMD}} build -t warc-indexer -f Containerfile ."

  prepare:solrwayback:
    desc: Move files from the solrwayback package to the solrwayback folder
    dir: solrwayback
    cmds:
      - cp ../solrwayback_package/tomcat-9/webapps/* .

  build:solrwayback:
    desc: Build the solrwayback image
    dir: solrwayback
    cmds:
      - "{{.IMAGEBUILD_CMD}} build -t solrwayback -f Containerfile ."

  prepare:solr:
    desc: Move files from the solrwayback package to the solr folder
    dir: solr
    cmds:
      - |
        if [ -d ./solr_home/ ] && [ -z ${delete+x} ]
        then
          echo -n 'solr_home already exists, should it be deleted and recreated? y/n: '
          read -r delete
        fi
        if [ $delete == 'y' ]
        then
          rm -r ./solr_home
        fi
        [ -d ./solr_home/ ] || cp -r ../solrwayback_package/solr-9/server/solr/ ./solr_home
