name: Build solrwayback and warc-indexer images

on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tasks to prepare for the build ⚙️
        run: task prepare:build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: SolrWayback Extract metadata (tags, labels) for Docker
        id: swb_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/deutsche-nationalbibliothek/solrwayback-compose
          flavor: |
            latest=auto
            prefix=solrwayback-
      - name: SolrWayback Build and push for many architectures
        id: swb_docker_build_tagged
        uses: docker/build-push-action@v5
        with:
          context: ./solrwayback
          file: ./solrwayback/Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: 'linux/amd64,linux/arm64/v8,linux/ppc64le'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.swb_meta.outputs.tags }}
          labels: ${{ steps.swb_meta.outputs.labels }}
      - name: WARC Indexer Extract metadata (tags, labels) for Docker
        id: widx_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/deutsche-nationalbibliothek/solrwayback-compose
          flavor: |
            latest=auto
            prefix=warc-indexer-
      - name: WARC Indexer Build and push for many architectures
        id: widx_docker_build_tagged
        uses: docker/build-push-action@v5
        with:
          context: ./warc-indexer
          file: ./warc-indexer/Containerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: 'linux/amd64,linux/arm64/v8,linux/ppc64le'
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.widx_meta.outputs.tags }}
          labels: ${{ steps.widx_meta.outputs.labels }}
